manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kriscables
      url-base: https://github.com/kriscables
  projects:
    - name: zmk
      remote: kriscables
      revision: sofle
      import: app/west.yml
  self:
    path: config
